name: "husky_setup"

paths:
  root_dir: ""

  image_folders:
    CAM_1: ""
    CAM_2: ""
    CAM_3: ""
    CAM_4: ""
    CAM_5: ""

  lidar_folder: ""

  calib_file: ""

cameras:
  - id: "CAM_1"
    name: "Front Center"
  - id: "CAM_2"
    name: "Front Left"
  - id: "CAM_3"
    name: "Front Right"
  - id: "CAM_4"
    name: "Rear Left"
  - id: "CAM_5"
    name: "Rear Right"

extensions:
  images: ".png"
  lidar: ".pcd"