segmentation:
  name: "SAM2"
  weights: "sam2_b.pt"
  device: "cuda"
  conf_threshold: 0.5

detection:
  name: "YOLOv11"
  weights: "yolov11_b.pt"
  conf_threshold: 0.5

tracking:
  name: "BotSORT"
  weights: "botsort_b.pt"
  conf_threshold: 0.5