defaults:
  - _self_

# Benchmark Settings
output_dir: "/home/soumoroy/SALT/MSALT_outputs_annotations_kitti/"
data_root: "/home/soumoroy/Downloads/semantic-kitty/sequences" # Path containing '00', '01', etc.
sequence_id: "00"                                              # String (SemanticKITTI uses "00", "01")
num_frames: 50
iou_threshold: 0.5                                             # IoU threshold for matching predictions to ground truth

# SemanticKITTI Label Mapping
label_mapping:
  moving_car: "Car"
  static_car: "Car"
  vehicle.car: "Car"
  
  moving_people: "Pedestrian"
  static_people: "Pedestrian"
  pedestrian: "Pedestrian"
  
  moving_truck: "Truck"
  static_truck: "Truck"
  truck: "Truck"
  
  moving_bus: "Bus"
  static_bus: "Bus"
  bus: "Bus"

  moving_cyclist: "Cyclist"
  static_cyclist: "Cyclist"
  cyclist: "Cyclist"

  Car: "Car"
  Bus: "Bus"
  Truck: "Truck"
  Pedestrian: "Pedestrian"
  Cyclist: "Cyclist"